server:
  port: 8802
 
spring:
  application:
    name: department-application  

eureka:
  instance:
    appname: department-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      



              